version: "3.9"
services:
  # api:
    # hostname: api
    # build:
      # dockerfile: ./RedacteurPortaal.Api/Dockerfile
      # args:
        # username: $USERNAME
        # password: $PASSWORD
    # ports:
      # - "80:80"
    # environment:
      # - ASPNETCORE_URLS=http://+:80
    # network_mode: host
  portaal_db:
    hostname: portaal_db
    image: postgres:14.1-alpine
    restart: always
    container_name: portaal_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=RedactiePortaal.Data
    ports:
      - "5433:5432"
    expose:
      - "5433:5432"
    volumes: 
      - portaal_db:/var/lib/postgresql/data
  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    - discovery.type=single-node
  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.9.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
# VOLUMES
volumes:
  portaal_db:
    driver: local
  elasticsearch-data: