name: NuGet Generation

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/Redactie-Portaal/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
          
      - name: Build solution and generate NuGet package
        run: | 
          cd RedacteurPortaal.Grains
          dotnet build -c Release
          dotnet pack -c Release -o out -p:PackageVersion=1.0.${{ github.run_number }} 
      - name: Push generated package to GitHub registry
        run: |
          cd RedacteurPortaal.Grains
          dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true --api-key ${{secrets.GITHUB_TOKEN}}       
